kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule-jimmys
  ports:
  - protocol: TCP
    port: 8800
    nodePort: 32000
    targetPort: 8900

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule-jimmys
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule-jimmys
  template:
    metadata:
      labels:
        app: train-schedule-jimmys
    spec:
      containers:
      - name: train-schedule-jimmys
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8900
